[package]
name = "migration-rocksdb"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.4"
macros = { path = "../../util/macros" }
kvdb = "0.7.0"
kvdb-rocksdb = "0.9.0"

[dev-dependencies]
tempdir = "0.3"
